### ISSUE TITLE
Flash of Unstyled Content with Webpack 4

### ISSUE THREAD

**Issue by ithinkdancan** [catamphetamine/universal-webpack#94]
The instructions for preventing a [flash of unstyled content](https://github.com/catamphetamine/universal-webpack#flash-of-unstyled-content) appears to be incompatible with webpack 4 setup as it still seems to rely on extract-text-plugin. even using `useMiniCssExtractPlugin` prevents the CSS from being bundled with the app for hot reloading. Is there still a way to extract the CSS and still keep it bundled in the app while using `useMiniCssExtractPlugin`?

`UniversalWebpack.client_configuration(configuration, settings, { development: true, css_bundle: 'main.css' });`

**Comment by catamphetamine** [comment]
Yeah, `mini-css-extract-plugin` doesn't work with the old way.
Because it doesn't support the option of both extracting the styles into a CSS bundle and also leaving them there for `style-loader` (`remove: false` option of `extract-text-webpack-plugin`).
`mini-css-extract-plugin` seems to have "hot-reloadable styles" feature implemented, so I'll read about that and maybe come up with a better solution:
https://github.com/webpack-contrib/mini-css-extract-plugin#advanced-configuration-example
I'll leave a comment here later.

**Comment by catamphetamine** [comment]
Oh, actually, yeah, it still has "TODO: HMR support" in the readme so `mini-css-extract-plugin` doesn't support HMR as of now.
Well, I guess just use smoke screen and `react-hot-loader` then.
